[package]
name = "nun-ui"
description = "Rendering, styling and terminal lifecycle for nun"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
crossterm = "0.29.0"
nun-config = { version = "0.1.0", path = "../nun-config" }
nun-core = { version = "0.1.0", path = "../nun-core" }
nun-lsp = { version = "0.1.0", path = "../nun-lsp" }
nun-syntax = { version = "0.1.0", path = "../nun-syntax" }
nun-term = { version = "0.1.0", path = "../nun-term" }
nun-theme = { version = "0.1.0", path = "../nun-theme" }
nun-workspace = { version = "0.1.0", path = "../nun-workspace" }
pulldown-cmark = { version = "0.13.4", default-features = false }
ratatui = "0.30.2"
ropey = { version = "1.6.1", default-features = false, features = ["simd"] }
signal-hook = "0.4.4"
unicode-segmentation = "1.13.3"
unicode-width = "0.2.2"

[dev-dependencies]
proptest = "1.11.0"

[target.'cfg(unix)'.dependencies]
rustix = { version = "1.1.4", features = ["std", "termios"] }
