[package]
name = "nun"
description = "A mouse-first terminal code editor that inherits your terminal's colors"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
crossterm = "0.29.0"
nun-config = { version = "0.1.0", path = "../nun-config" }
nun-core = { version = "0.1.0", path = "../nun-core" }
nun-input = { version = "0.1.0", path = "../nun-input" }
nun-theme = { version = "0.1.0", path = "../nun-theme" }
nun-ui = { version = "0.1.0", path = "../nun-ui" }
ratatui = "0.30.2"
unicode-segmentation = "1.13.3"
unicode-width = "0.2.2"

[dev-dependencies]
tempfile = "3.27.0"
